name: CI/CD Pipeline

on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev" ]
  workflow_dispatch:

jobs:
  LINT:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: "temurin"
          
      - name: Get Permissions
        run: chmod +x ./gradlew

      - name: Lint
        run: ./gradlew lintDebug

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4.3.3
        with:
          name: LintReport.html
          path: app/build/reports/lint-results-debug.html
          
  UNIT-TESTS:
    needs: [LINT]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: "temurin"
          
      - name: Get Permissions
        run: chmod +x ./gradlew

      - name: UnitTest
        run: ./gradlew test

      - name: Upload UnitTest Report
        uses: actions/upload-artifact@v4.3.3
        with:
          name: UnitTestReport
          path: app/build/reports/tests/testDebugUnitTest/
          
  APK:
    needs: [UNIT-TESTS]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: "temurin"
          
      - name: Get Permissions
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: TodoApp.apk
          path: app/build/outputs/apk/debug/app-debug.apk
